version: "3.3"

services:
  syslog:
    container_name: syslog
    image: balabit/syslog-ng:latest
    ports:
      - "514:514/udp"
      - "601:601/udp"
      - "6601:6601/tcp"
    # Volumes store your data between container upgrades
    volumes:
    - './syslog/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf'
    restart: unless-stopped
